[versions]
androidx-core-ktx = "1.13.0"
appcompat = "1.6.1"
kotlin-serialization = "1.6.3"
maven-publish = "0.28.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }

[plugins]
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
